backend:
  name: git-gateway
  branch: admin-panel

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "src/content/pages/home.md" # Przykładowa ścieżka do treści w Astro Content Collections
        label: "Strona Główna"
        name: "home"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Opis", name: "description", widget: "text" }
          - { label: "Treść", name: "body", widget: "markdown" }